### PR TITLE
Switch up compiler directives for concurrency

### PR DESCRIPTION
**Pull request by joshuawright11**
This may be misguided, see comments in #110

### CODE REVIEW

**Comment by tomerd** [comment]
@ktoso is this the right approach?

**Comment by joshuawright11** [comment]
Seeing as CI is failing, I assume the tests are all running on an OS where `_Concurrency` is available.  Added `compiler(>=5.5)` to the conditionals.

**Review by ktoso — COMMENTED** [review]
This is _partially_ correct.

- We should _remove_ any mention of `import _Concurrency` at all; completely. This module is imported automatically when it exists. It should not be imported explicitly - it just adds more noise to the project.

- The `#if` guard IS correct though for guarding any code _actually using async/Concurrency_, we can't just detect the swift version but have to guard with the concurrency import availability as well.

Would you mind changing the PR to remove the imports? Then it's LGTM :)

**Comment by adam-fowler** [comment]
Once Monterey is out should we still be checking for existence of _Concurrency. Is this a temporary fix until that point?

**Comment by ktoso** [comment]
For now assume it'll be around.

**Comment by joshuawright11** [comment]
Great, thanks @ktoso. Just pushed.

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
thanks @joshuawright11 something does not seem to be correct with the conditions give the CI failures in > 5.2 < 5.5 version

**Comment by ktoso** [comment]
Something is indeed weird here... I was checking with the compiler team if these are the guards we should use and we think those are right 🤔

**Comment by tomerd** [comment]
I had trouble composing them in the past, hence the guards

**Comment by joshuawright11** [comment]
Yeah it does seem like something odd is going on, I poked around with the complex #if statements on my machine and it worked fine; though my machine is also 5.5 so perhaps it's an issue with older swift versions.

Alas, `guard #canImport(_Concurrency)` gave an `error: use of unknown directive '#canImport`, so I split up the if statement further to:

```swift
#if compiler(<5.2)
return
#elseif compiler(<5.5)
throw XCTSkip()
#elseif !canImport(_Concurrency)
throw XCTSkip()
#else
...
#endif
```

Let's see if it likes that.

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
> Yeah it does seem like something odd is going on, I poked around with the complex #if statements on my machine and it worked fine; though my machine is also 5.5 so perhaps it's an issue with older swift versions.

fyi you can run the tests we run in CI locally using docker, see the docker-compose files

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
nightly CI failure expected due to @sendable changes

**Pull request merged**
