### PR TITLE
Express backtrace as a LifecycleTask

### PR DESCRIPTION
**Pull request by hassila**
**Motivation**
Refactor to use LifecycleTask to start the Backtrace according to https://github.com/swift-server/swift-service-lifecycle/issues/35

**Changes**
Deferred installation of Backtrace from init to instead use a LifecycleTask.

**Results**
Backtrace is started slightly later in the startup chain (e.g. after setting up signal handlers) - should be ok though, it will be the first installed task.

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-server-bot add to whitelist

**Comment by tomerd** [comment]
thanks for the PR @hassila! I have mixed feeling about this idea (the implementation is great!) -- having the backtraces installed as soon as possible is desired since event the initial setup may cause a crash and without the backtraces installed we would not get backtraces on those

**Comment by tomerd** [comment]
@swift-server-bot add to allowlist

**Comment by hassila** [comment]
Yeah, I also thought about that - but figured it would be ok in terms of tradeoff as we will be the absolutely first handler installed - the window of "opportunity" for things to fail is a very small initial path while we are setting up - and then we would have died very early indeed - in practice a release worthy version of the library shouldn't keel over there (as a user I'd be ok with resorting to running it in the debugger if that ever would happen in practice - I'd probably see if usable core files were an option for such cases).

**Comment by hassila** [comment]
Or to put it another way - I would expect 99.9999% of all actual crashes happen later due to users of the framework doing something bad... (famous last words, I know)

**Comment by hassila** [comment]
@tomerd In the same vein, I would propose to move the installation of signal handles to also be LifecycleTasks and install them directly after backtrace in a similar way. That would also decrease the amount of code being run before backtrace is installed.

**Comment by tomerd** [comment]
setting up the shutdown signal handler sounds good first step, backtraces are still better as a discrete first action imo

**Comment by hassila** [comment]
That's absolutely fine of course, closing this one. Opened https://github.com/swift-server/swift-service-lifecycle/pull/88 for the signal handler installation for consideration.

**Pull request closed without merging**
