### PR TITLE
Tweak README.

### PR DESCRIPTION
**Pull request by Sajjon**
`"shutdown"` (which is the noun) -> `"shut down"` (the verb, which is intended)
`"top level"`-> `"top-level"` (this might just be my personal preference)
`"using  a"` -> `"using a"` (removed double space)
`"This is especially useful for application running on"`-> `"for applicationS running"` (missing article)
`"Use 'start' function"` -> `"Use the 'start' function"`(missing article)
`"Typical use of the library"` -> `"The typical"` (missing article, alternatives: "A typical", however, it is too close to the antonym "atypical" 😃)

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
thanks again @sajjon

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Pull request merged**
