### PR TITLE
Bump minimum Swift version to 5.7

### PR DESCRIPTION
**Pull request by rnro**
Motivation:

Now that Swift 5.9 is GM we should update the supported versions and remove 5.6

Modifications:

* Update `Package.swift`
* Delete the <5.7 docker compose files and make a 5.10 one
* Update the 5.9 docker file to stop using nightlies

Result:

Remove support for Swift 5.6, add 5.10

### CODE REVIEW

**Comment by FranzBusch** [comment]
@swift-server-bot add to allowlist

**Review by FranzBusch — APPROVED** [review]

**Review by ktoso — APPROVED** [review]
LGTM

**Comment by rnro** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by rnro** [comment]
@yim-lee Could you please update the CI here too?

**Comment by yim-lee** [comment]
CI updated. @swift-server-bot test this please

**Comment by FranzBusch** [comment]
@yim-lee any idea why we are continuing to time out on the 5.7 CI? This wasn't the case a few days back and it seems to be stuck during linking. Is this an issue with the node?

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
Hmm, the 5.7 job timed out on three different nodes, then it just ran on yet another node and finished under 40s. I ran CI cleanup job before which might have helped? Not sure.

@swift-server-bot test this please

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
With https://github.com/swift-server/swift-service-lifecycle/pull/160/commits/ddee4adce3740022000f8f5574d803dbb22337d8, the 5.7 job has passed two times on one of the nodes that it failed on before. Maybe it's that?

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
A couple of test failures in 5.9: https://ci.swiftserver.group/job/swift-service-lifecycle-swift59-prb/62/console

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
I don't know what causes 5.7 build to stuck sometimes.

Some observations:
- It seems to always build successfully right after I touch the job config (agents 6 and 5). 
- So far the job always fails on agent 4 and subsequent runs fail, even on different agent (agent 5).
- It _might_ continue to run fine after a successful run if subsequence runs stayed on the same agent (2 consecutive successful runs on agent 5).
- I don't think it's agent specific because 5.10 ran fine on agent 4.

**Comment by FranzBusch** [comment]
Thanks for investigating this a bit @yim-lee. Let's merge this and keep an eye on it.

**Pull request merged**
